@component('mail::message')
# Hi {{$user->first}},

Thank you for you for joining the Sonsic waitlist!  
<br>
While you'll be the first to know all of the latest Sonsic news, 
make sure to follow our social media below to always stay up to date!

@component('mail::buttons', [
    'headline' => 'Follow us on social media',
    'buttons' => [
        [
            'url' => 'https://www.facebook.com/people/Sonsic/100094326226340/',
            'slot' => 'Facebook',
        ],[
            'url' => 'https://twitter.com/SonsicAR',
            'slot' => 'Twitter',
        ],[
            'url' => 'https://www.instagram.com/sonsicmarketing/',
            'slot' => 'Instagram',
        ],[
            'url' => 'https://www.tiktok.com/@sonsicmarketing?lang=en',
            'slot' => 'TikTok',
        ],[
            'url' => 'https://www.youtube.com/channel/UCyypetZiJyQUtXqHBU2CUgg',
            'slot' => 'Youtube',
        ]
    ]
])
@endcomponent

We look forward to working with you,<br>
The Sonsic Team
<br><br>
This email is generated by the Sonsic emailing system.
<br>
Please do not reply.

@endcomponent
